
import React from 'react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Share, Download, FileImage, FileText } from 'lucide-react';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { useToast } from '@/hooks/use-toast';

interface ShareReportButtonProps {
  sensorData: {
    aqi: number;
    temperature: number;
    humidity: number;
    pm2_5: number;
    pm10: number;
    timestamp: string;
  };
  location?: string;
}

export const ShareReportButton: React.FC<ShareReportButtonProps> = ({ 
  sensorData, 
  location,
}) => {
  const { toast } = useToast();

  const getAQILevel = (aqi: number) => {
    if (aqi <= 50) return { level: 'Good', color: '#10b981' };
    if (aqi <= 100) return { level: 'Moderate', color: '#f59e0b' };
    if (aqi <= 150) return { level: 'Unhealthy for Sensitive Groups', color: '#f97316' };
    if (aqi <= 200) return { level: 'Unhealthy', color: '#ef4444' };
    if (aqi <= 300) return { level: 'Very Unhealthy', color: '#a855f7' };
    return { level: 'Hazardous', color: '#dc2626' };
  };

  const exportAsPNG = async () => {
    try {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      
      if (!ctx) return;
      
      canvas.width = 800;
      canvas.height = 700;
      
      // Background gradient
      const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
      gradient.addColorStop(0, '#1a1a2e');
      gradient.addColorStop(1, '#16213e');
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      
      // Header
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 28px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('🌍 Air Quality Report', canvas.width / 2, 50);
      
      // Location and timestamp
      ctx.font = '16px Inter, sans-serif';
      ctx.fillStyle = '#94a3b8';
      ctx.fillText(`📍 ${location}`, canvas.width / 2, 80);
      ctx.fillText(`🕒 Generated: ${new Date(sensorData.timestamp).toLocaleString()}`, canvas.width / 2, 105);
      
      // AQI Section
      const aqiInfo = getAQILevel(sensorData.aqi);
      ctx.fillStyle = aqiInfo.color;
      ctx.font = 'bold 48px Inter, sans-serif';
      ctx.fillText(`${sensorData.aqi}`, canvas.width / 2, 180);
      
      ctx.fillStyle = '#ffffff';
      ctx.font = 'bold 20px Inter, sans-serif';
      ctx.fillText('Air Quality Index', canvas.width / 2, 210);
      
      ctx.fillStyle = aqiInfo.color;
      ctx.font = '16px Inter, sans-serif';
      ctx.fillText(`${aqiInfo.level}`, canvas.width / 2, 235);
      
      // Metrics grid
      const metrics = [
        { label: '🌡️ Temperature', value: sensorData.temperature, unit: '°C', x: 200, y: 320 },
        { label: '💧 Humidity', value: sensorData.humidity, unit: '%', x: 600, y: 320 },
        { label: '☁️ PM2.5', value: sensorData.pm2_5, unit: 'μg/m³', x: 200, y: 420 },
        { label: '🌫️ pm10', value: sensorData.pm10, unit: 'μg/m³', x: 600, y: 420 }
      ];
      
      metrics.forEach((metric) => {
        ctx.fillStyle = '#ffffff';
        ctx.font = '16px Inter, sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(metric.label, metric.x, metric.y);
        
        ctx.font = 'bold 24px Inter, sans-serif';
        ctx.fillStyle = '#60a5fa';
        ctx.fillText(`${metric.value}${metric.unit}`, metric.x, metric.y + 30);
      });
      
      // Footer
      ctx.fillStyle = '#64748b';
      ctx.font = '12px Inter, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Generated by Local Air Quality Monitor', canvas.width / 2, canvas.height - 30);
      ctx.fillText('Data collected from ESP32 environmental sensor', canvas.width / 2, canvas.height - 15);
      
      // Download
      const link = document.createElement('a');
      link.download = `air-quality-report-${new Date().toISOString().split('T')[0]}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      
      toast({
        title: "Report Exported",
        description: "Professional air quality report has been downloaded as PNG.",
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Failed to export report as PNG.",
        variant: "destructive"
      });
    }
  };

  const exportAsPDF = () => {
    const aqiInfo = getAQILevel(sensorData.aqi);
    
    const reportText = `
🌍 AIR QUALITY REPORT
====================

📍 Location: ${location}
🕒 Generated: ${new Date(sensorData.timestamp).toLocaleString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 AIR QUALITY INDEX (AQI)
Current Level: ${sensorData.aqi} - ${aqiInfo.level}

Health Implications:
${aqiInfo.level === 'Good' ? '✅ Air quality is satisfactory, and air pollution poses little or no risk.' :
  aqiInfo.level === 'Moderate' ? '⚠️ Air quality is acceptable. However, there may be a risk for some people.' :
  aqiInfo.level.includes('Unhealthy') ? '❌ Everyone may begin to experience health effects.' :
  '🚨 Health alert: The risk of health effects is increased for everyone.'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 DETAILED METRICS

🌡️ Temperature: ${sensorData.temperature}°C
   Status: ${sensorData.temperature >= 20 && sensorData.temperature <= 25 ? 'Comfortable' : 
            sensorData.temperature < 20 ? 'Cool' : 'Warm'}

💧 Humidity: ${sensorData.humidity}%
   Status: ${sensorData.humidity >= 30 && sensorData.humidity <= 60 ? 'Optimal' : 
            sensorData.humidity < 30 ? 'Low' : 'High'}

☁️ PM2.5: ${sensorData.pm2_5} μg/m³
   Status: ${sensorData.pm2_5 <= 12 ? 'Good' : sensorData.pm2_5 <= 35 ? 'Moderate' : 'Unhealthy'}

🌫️ pm10: ${sensorData.pm10} μg/m³
   Status: ${sensorData.pm10 <= 54 ? 'Good' : sensorData.pm10 <= 154 ? 'Moderate' : 'Unhealthy'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 RECOMMENDATIONS
• Monitor air quality regularly
• Consider indoor air purification if AQI > 100
• Limit outdoor activities during poor air quality
• Keep windows closed during high pollution periods

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Local Air Quality Monitor
Data collected from ESP32 environmental sensor
    `;
    
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.download = `air-quality-report-${new Date().toISOString().split('T')[0]}.txt`;
    link.href = URL.createObjectURL(blob);
    link.click();
    
    toast({
      title: "Report Exported",
      description: "Detailed air quality report has been downloaded.",
    });
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="glass-button">
          <Share className="h-4 w-4" />
          Share Report
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportAsPNG}>
          <FileImage className="h-4 w-4 mr-2" />
          Export as PNG
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsPDF}>
          <FileText className="h-4 w-4 mr-2" />
          Export as Report
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
